### ISSUE TITLE
Upwards compatibility for mta-sts.json

### ISSUE THREAD

**Issue by treibholz** [mrisher/smtp-sts#116]
Scenario: "in the future, we will design STSv2".
For compatibility and migration-reasons, I would have to announce both, this might end up in a problem, for older STSv1-only implementations.

I'll make up a potential STSv2, to explain:

The TXT records would the look similar to this:

```
"v=STSv1\; id=12345\;"
"v=STSv2\; id=234567\; key=0x12341\;"
```

The mta-sts.json would then have to be at another place. I'm not sure what is the best way to solve this:
1. add the version to the path. (/.well-known/v1/mta-sts.json)
2. add the version to the filename. (/.well-known/mta-sts-v1.json)
3. keep it where it is and make sure even v1-implementations can handle (or ignore) multiple objects:

``` json
{
  "version": "STSv1",
  "mode": "enforce",
  "mx": ["*.mail.example.com"],
  "max_age": 123456
},
{
  "version": "STSv2",
  "inbound-mode": "enforce",
  "outbound-mode": "report",
  "mx": {
    "*.mail.example.com" : "TLSA 3 1 1 1691EDF7B8A48AB155D068B28DB7BC759B869BD34D6E32204F782BF708A2F4C3 DEADBEEF"
  },
  "max_age": 123456
}
```
1. or change the format of mta-sts.json, so an implementation is forced to use a specific version:

``` json
{
  "STSv1": {
    "mode": "enforce",
    "mx": ["*.mail.example.com"],
    "max_age": 123456
  },
  "STSv2": {
    "inbound-mode": "enforce",
    "outbound-mode": "report",
    "mx": {
      "*.mail.example.com" : "TLSA 3 1 1 1691EDF7B8A48AB155D068B28DB7BC759B869BD34D6E32204F782BF708A2F4C3 DEADBEEF"
    },
    "max_age": 123456
  }
}
```

The longer I think about it, the more I prefer the option 1 (or 2). It feels more robust, easier to implement and harder to to implement it wrong, also bad v1-implementations couldn't break.

What do you think?

**Comment by abrotman** [comment]
I think it should be in the body of the policy.  If we have a different version, it's easy enough to add a second section to the policy on the hosting server.

**Comment by danmarg** [comment]
I agree with @treibholz that splitting the path seems more robust. In the future, we may not want to use JSON! 

On the other hand, I would argue that:

1. We can make non-breaking changes to the existing policy. Likely changes in the future would be things like cipher or TLS versioning (or other additional constraints, like your example of "outbound-mode"). In such a case, we can simply add fields to the existing policy file, since those MUST be ignored by compliant implementations of v1. 

2. Worst case, we can add a new path (.well-known/mta-sts-v2.json) without modifying the current path. 

So I'm slightly lazy about making this change (both in our implementation and in the spec), but I could be convinced otherwise if you feel strongly about it.

**Comment by prbinu** [comment]
I think there are 2 cases here:
1. A non-breaking change or a revision of existing policy. In this case, I agree with what Dan said. 
2. An incompatible version change. I think adding a version to path / file name are good options. 

In either case, we can be lazy now, and add these changes when we update the policy next time

**Comment by danmarg** [comment]
OK, let's close this for now then. Please reopen if I'm off the mark.
