### ISSUE TITLE
Merge tlsrpt Section 7 points

### ISSUE THREAD

**Issue by prbinu** [mrisher/smtp-sts#145]
Followup issue ticket on AD review of draft-ietf-uta-smtp-tlsrpt-04.txt

====
Section 7:

    o  Flooding of the Aggregate report URI (rua) endpoint: An attacker
      could flood the endpoint and prevent the receiving domain from
      accepting additional reports.  This type of Denial-of-Service
      attack would limit visibility into STARTTLS failures, leaving the
      receiving domain blind to an ongoing attack.

  [...]

    o  Reports as DDoS: TLSRPT allows specifying destinations for the
      reports that are outside the authority of the Policy Domain, which
      allows domains to delegate processing of reports to a partner
      organization.  However, an attacker who controls the Policy Domain
      DNS could also use this mechanism to direct the reports to an
      unwitting victim, flooding that victim with excessive reports.
      DMARC [RFC7489] defines an elegant solution for verifying
      delegation; however, since the attacker had less ability to
      generate large reports than with DMARC failures, and since the
====
Question:   Are these talking about the same issue? If yes, they should be merged 
or one of them should be deleted.

**Comment by danmarg** [comment]
I don't believe they are. The former is talking about a DoS against the endpoint itself, whereas the latter is talking about the risks of triggering reports from innocent parties as a mechanism to make those parties launch a DoS. 

I do think the explanation for why Reports as DDoS is not a risk is lacking a bit. The real crux, IMO, is that in DMARC the reports are sent by the recipient of the email being reported, whereas in TLSRPT they are sent by the sender; as such, the only way to get someone to send a report somewhere else is to first get them to send you mail. Is it worth adding this as a clarification? 

I mention this mostly because the topic came up at the IETF discussion, and it took me a moment to dredge up why I thought this was not a concern. But I think the topic came up from someone who had also not read this section closely (as I had not).

**Comment by prbinu** [comment]
> Is it worth adding this as a clarification?
that would be better (or rephrase the desc)

**Comment by danmarg** [comment]
Yes, possibly.  :)

**Comment by danmarg** [comment]
61d5cf7
