### ISSUE TITLE
Feedback request - _smtp-tlsrpt

### ISSUE THREAD

**Issue by prbinu** [mrisher/smtp-sts#150]
Here is the DNS record for tlsrpt:
```
_smtp-tlsrpt.mail.example.com. IN TXT \
        "v=TLSRPTv1;rua=mailto:reports@example.com"
```

Would it be a good idea if we can remove `_smtp-` prefix to make this RFC proposal more generic and applicable to other protocols?

**Comment by danmarg** [comment]
Well, HPKP has its own reporting mechanism, and as we all know (slightly tongue in cheek), the Internet is for SMTP and HTTP and nothing else. 

More seriously, while I don't have any problems with that per se, it feels to me that at this stage it's easiest to get agreement on a specific and somewhat narrower design; opening it up to general-purpose use will make it hard to achieve consensus (due to the potentially myriad uses). 

Anyway, that's my 0.02CHF. ;)

**Comment by abrotman** [comment]
There might even be an advantage to leaving the _smtp prefixed.  If this were to be used for other feedback mechanisms, they may have different destinations.

**Comment by prbinu** [comment]
Ok. 
Closing the ticket :-)
