### ISSUE TITLE
Unknown extensions before the id field (TXT record)

### ISSUE THREAD

**Issue by aykevl** [mrisher/smtp-sts#167]
This is a snippet from the current ABNF on the TXT record:

    sts-text-record = sts-version field-delim sts-id
                      [field-delim [sts-extensions]]

But let's imagine we'll introduce key `x` in the future, with some value `something`. In the current form, this should be written like:

    v=STSv1; id=10; x=something;

But what about this?

    v=STSv1; x=something; id=10;

In the current form it's invalid, but as the TXT record is used as a set of key/value pairs it looks like it should be possible like in [DKIM and DMARC](https://tools.ietf.org/html/rfc6376#section-3.2) (SPF uses a slightly different format). Maybe the ABNF should be adjusted to allow these sort of extensions.

See also: df50d59c0db3428d3bb247a3e90cdfa918f4f4dd

**Comment by danmarg** [comment]
I commented similarly on https://github.com/mrisher/smtp-sts/issues/174, but I think this is because the ABNF strictly specifies required fields.

An easy option (and how it's done in the DKIM RFC) is to specify the syntax of fields--their structure, names and values--but not semantics (i.e. repetition, being required) in the ABNF and, instead, specify "required" or "repeated" in plain text. 

I'm OK with that. Shrug. Thoughts?

**Comment by danmarg** [comment]
b683498a0cf8f100ce45ef7d2b5028c48e97f501
