### ISSUE TITLE
Strict ABNF for policy file format

### ISSUE THREAD

**Issue by aykevl** [mrisher/smtp-sts#174]
The ABNF for the policy file format seems very strict to me:

1. it does not allow reordering of lines (e.g. max_age before mx)  
  I don't really care about this, but a specific order may be unexpected as it is not required in most other key/value file formats (email headers, HTTP headers, JSON dict).
2. it only allows CRLF as newlines  
  While in theory the "text/*" mimetype [only allows CRLF](https://tools.ietf.org/html/rfc2046#section-4.1.1), in practice this is mostly ignored and text files on the web use both CRLF and LF (e.g. in HTML files). Requiring CRLF makes it more difficult to write files on non-Windows platforms.
3. it is not allowed to insert an empty line anywhere in the file or to add a newline at the end of the file  
  This breaks most text editors on POSIX-like platforms (e.g. vim). They expect that any line in a text file ends with a newline.
4. it is not allowed to add whitespace at the end of a line (or at the beginning)

Also see this email by Viktor: https://mailarchive.ietf.org/arch/msg/uta/50MVZr5GpTyILEhv0gpYtl6saYg/?qid=b39f8d24e08441c3d69f7fa4e9d23c1f

**Comment by danmarg** [comment]
1. Agreed, this is overly strict. I wrote it this way to specify clearly that you must have each of the required keys once; otherwise, to express this with a context-free grammar, I think you have to do something like
```
policy-record  = (version mode 1*(mx) max-age) /
                          (mode version 1*(mx) max-age) /
                          (1*(mx) mode version max-age) / ; etc, through all combinations
```
Though I may be wrong. Alternatively, we can just have the BNF omit what fields are required for brevity's sake and do

`[version / mode / mx / max-age]`

Or is there a cleaner way to do this?

2. The list discussed briefly the CRLF vs LF thing: https://www.ietf.org/mail-archive/web/uta/current/msg02057.html. Please weigh in there. I'm OK with saying that "a tolerant parser SHOULD accept LF", but I'm not sure that addresses your request; Alexey had requested the opposite, after all. 

3. Thanks; I've added an optional CRLF at the end of the file. We can also add optional arbitrary CRLF between lines, but I'm not sure that's useful. Thoughts?

4.  Sure, WSP at the end is easy enough. I think we should disallow at the beginning to allow parsers to be simpler (though it's trivial, with most string libraries, to be tolerant of whitespace here). 

032205d
https://github.com/mrisher/smtp-sts/pull/179

Thoughts?

**Comment by aykevl** [comment]
1. They had a very simple solution for DMARC: https://tools.ietf.org/html/rfc7489#section-6.4. But I'm very now to the IETF and how things work here, so I don't really know.
2. I don't really care. Parsing gets a bit harder when both LF and CRLF are allowed, but in practice most HTTP and SMTP servers will accept LF anyway (tested Postfix and Gmail). Maybe the authors of MTAs know best.
3. Not sure about empty lines either. I don't see their usefulness, but they won't really hurt either.
4. Agree. Now there's only whitespace allowed around the value, not around the key.

**Comment by danmarg** [comment]
1. Yes, but this doesn't specify which fields are required. I don't know what we'd prefer for this. Switching to a looser grammar and specifying the semantics separately seems fine to me, so I will do that. 

2. Beats me. I defer to the feedback on the list. I suspect implementors will be more tolerant anyway--my own code was. (The same observation goes for the above, FWIW.)

3. Agreed. I can add them in. 

Thanks again for the feedback. Notes to self:

1 and 3 above require an edit.

**Comment by danmarg** [comment]
Actually, regarding the DMARC version, they actually are (per ABNF) specifying an order, and then they have the commnet
```
   ; components other than dmarc-version and
   ; dmarc-request may appear in any order
```

Is that to which you were referring? Of course that violates the ABNF (in the sense that they have an ABNF which says tone thing and a comment that contradicts it). 

We might as well just have the ABNF be *more* tolerant and then specify the semantics separately, I think.

**Comment by danmarg** [comment]
b683498
