### ISSUE TITLE
Reduce depth of FQDN: use policy-mta-sts.$(DOMAIN) FQDN rather than policy.mta-sts.$(DOMAIN) to host STS policy

### ISSUE THREAD

**Issue by eyeofthenico** [mrisher/smtp-sts#60]
The main reason for this is to simplify hosting of policy as it can be then served with a certificate for *.example.com rather than requiring a dedicated cert (as *.example.com only goes one level deep).
Requiring a dedicated cert for FQDN makes it more painful to manage and renew, especially as it is only used to serve a single file.
I understand this may introduce concern for a service that allows user to post their own content on *.example.com, which would enable issue, but at the same time, the policy requires DNS verification.

**Comment by mrisher** [comment]
that's a good point, that since you [currently] need to register the DNS as
well as the subdomain, a rogue end-user posting a fraudulent policy at *.
dyndns.org or *.geocities.com is less of a threat.

**Comment by danmarg** [comment]
You mean the TXT record?

I don't know. It means DNS injection + controlling the subdomain =
persistent DoS (at least until the operator publishes a new policy, which
fortunately they can do since they just need *some* cert for their domain
to update a policy).

DNS injection today can lead to a DoS as long as the DNS TTL. But the above
seems worse; that was always my fear. I don't know how realistic it is.

**Comment by jjones425** [comment]
Dan, can you close out on this one. If we do not feel it's a good idea let's close as won't fix and communicate back to the submitter. Thanks.

**Comment by danmarg** [comment]
https://github.com/mrisher/smtp-sts/pull/101
