### ISSUE TITLE
Clarify that (if) HTTP redirects should be followed when retrieving policy

### ISSUE THREAD

**Issue by davidillsley** [mrisher/smtp-sts#61]
When retrieving ```https://policy.mta-sts.example.com/.well-known/mta-sts/current```, should clients follow standards HTTP redirects? I'd argue yes, to allow for management of the actual file somewhere else, but I can imagine some hesitation or uncertainty by implementors. It'd be good to have clarity in the spec.

**Comment by eyeofthenico** [comment]
Agree. This sounds very reasonable. Obviously no downgrade to HTTP,  right?
Should there be a limit in number of redirects though?

**Comment by prbinu** [comment]
Redirection may not be required because of following reasons:
1. The policy is already hosted on a sub-domain - that means you may outsource it if required to a 3rd party. In addition, you may use SNIs to share the server
2. We still need per-domain policy - hence there is not real benefit it doing so. Or there should be an option for some kind of policy includes. 
3. Additional complexity. following redirect may create security vulns (if not careful, like the one mentioned above)

This would be a good thing to discuss, especially when we need to manage large number of policy domains, but we haven't reached there yet.

**Comment by jjones425** [comment]
@danmarg @eyeofthenico do you agree with Binu's feedback?

**Comment by danmarg** [comment]
I don't have a strong feeling about it. If done properly I don't see a security risk here, but it is, I agree, extra complexity. I'm fine with a "no" if David doesn't object.

**Comment by danmarg** [comment]
There's also some minimal complexity this implies--for people already leery of integrating an HTTP client into their MTA, now there's redirect following? Since Binu seems to feel most strongly about this, I'm happy to just disallow. 

2bb178a

David/Nico, feel free to object; we can always revert.
