### ISSUE TITLE
IETF 96 - Describe State-Machine in more detail

### ISSUE THREAD

**Issue by jjones425** [mrisher/smtp-sts#72]
Describe State-Machine in more details

**Comment by mrisher** [comment]
I don't understand what's needed here. Anybody have a specific action item?

**Comment by jjones425** [comment]
Checking with Markus to see if he has more information.

**Comment by jjones425** [comment]
Mark, in looking back at the IETF notes, here is the reference I found.

V Dukhovni: Postfix probably no implementation until the spec is finalized. ID field needs multiple values so can do key rollover.
 State machine is underspecified per multiple MX.  Needs clarification re DANE.

**Comment by mlaber** [comment]
Hi Janet & Mark,

we got the feedback that we need a more detailed description of our state-machine.
The commentator inside and outside of our session meant with state machine the part or module of a  STS compliant MTA, which compares the cached STS policy with the parameters of the current transaction and leads to a result. In our case the result could be reject or report .

This could be tricky in a multi MTA scenario e.g. a domain with several (load balanced) MTA or multiple MS Exchange SMTP bridgeheads. A local caching of the policy could lead two path incosistensy when the mail is routed trough different MTAs, because  sts-max-age and the  DNS TTL are relative to the first contact of the sending MTA. During policy changes  MTA  A would rely on the cached but still valid policy and MTA B  with a “cold” cache will fetch  a potential newer and potential different policy.

To ensure that every MTA interprets the policy the same way at the same time a sort of distributed cache for the state machine will be needed eg. memcached.


imho this scenario is very theoretical, a typical corner case, using distributed caches will increase complexity in infrastructure and operations and cause more collateral damage than it helps.

Maybe we should cover this "multi MTA” case under security considerations to signal  our reviewers that we considered this scenario.
What´s your opinion? is this a suitable way to treat this issue? if you want i can add this two the Security Considerations in the draft  and send a PR within the next day.

Markus

**Comment by jjones425** [comment]
Adding @danmarg to comment.  I think adding this to the security considerations section could work.

**Comment by danmarg** [comment]
I think less in "security considerations" than its own section. I agree with Markus that we need not go into great detail about potentially complex scenarios where cache inconsistency would be a problem; instead, I think our goal should be to describe the policy application algorithm in such a way as to make clear that this isn't a problem. 

To be more specific, I think there are the following possibilities:

1. No policy. Duh. Uninteresting. 
2. No cached policy, policy found by MTA at send time, potential write-race on a shared policy cache. Not a problem; policies which match a current (even cached by the recursive resolver) TXT record whose TTL has not passed *must* still work; recipients can't assume the senders will fetch a newer policy. As such, write races are basically uninteresting. 
3. Cached policy and also updated policy discovered by a sender; potential write/read race on updating the cache versus reading from it on other sends. Similar to #2. 

One can go into more detail here, and there may be other permutations I haven't thought of, but I think that's the gist of the "state machine" request: to explain how cache consistency matters (or does not; I believe it does not). 

Am I making sense? I can take a stab at this at some point.

**Comment by jjones425** [comment]
What section would this be under, or, what would you call a new section? Would this be part of implementation since MTA scenarios could be different?

**Comment by prbinu** [comment]
**[1] State machine diagram for the main flow**
===================================

![image](https://cloud.githubusercontent.com/assets/6187435/17453103/7b571cb6-5b2b-11e6-967b-eb693b8a8771.png)

**[2] Policy cache/refresh flow**
========================
![image](https://cloud.githubusercontent.com/assets/6187435/17453083/2a6adef0-5b2b-11e6-8d21-afb9d96da89b.png)

**[3] Policy validation flow**
====================
![image](https://cloud.githubusercontent.com/assets/6187435/17453090/5f88fae0-5b2b-11e6-8b2b-bbeb388f57ea.png)

**Comment by DizzyGillespie** [comment]
The problem with this is the "policy valid = no" flow. It means that you can only make breaking changes to your MX once the last served policy has expired (whereas in the current design you can make breaking changes at any time as long as you are serving a new policy). 

The obvious implication of this compromise is that policy max_ages have to be fairly short--probably a day is reasonable. The obvious implication of this is that once a day a MITM gets an opportunity. 

I don't particularly like that tradeoff, but even if I did, I think this is a fairly major change and I would really hesitate to make it this late in the game. 

In comparison, I do believe the change Nico is making is functionally immaterial (i.e. it doesn't change the number of DNS or HTTP lookups or change the implementation in any real way). Am I mistaken?

(I agree there's a bit of complexity in STS as written around TTLs and refreshes, which is absolutely something to try to clarify, but the complexity actually buys something specific: the ability to use a longer policy expiration time!)

**Comment by danmarg** [comment]
The problem with this is the "policy valid = no" flow. It means that you can only make breaking changes to your MX once the last served policy has expired (whereas in the current design you can make breaking changes at any time as long as you are serving a new policy).

The obvious implication of this compromise is that policy max_ages have to be fairly short--probably a day is reasonable. The obvious implication of this is that once a day a MITM gets an opportunity.

I don't particularly like that tradeoff, but even if I did, I think this is a fairly major change and I would really hesitate to make it this late in the game.

In comparison, I do believe the change Nico is making is functionally immaterial (i.e. it doesn't change the number of DNS or HTTP lookups or change the implementation in any real way). Am I mistaken?

(I agree there's a bit of complexity in STS as written around TTLs and refreshes, which is absolutely something to try to clarify, but the complexity actually buys something specific: the ability to use a longer policy expiration time!)

**Comment by danmarg** [comment]
>  Once the policy is cached, you may not need to do DNS TXT lookup, instead you directly refresh the policy from HTTPS location. I would expect the policy ideally get refreshed once a day.

Also, this glosses over a key detail: how does the policy get refreshed once a day in this scenario? 

We have not actually specified that senders SHOULD or MUST get new policies ever as long as the cached policy is valid, which I believe is appropriate: because recipients cannot reason about whether all senders have gotten a new policy or purged their caches, they can never assume old policies are invalidated in any way. 

But if we wanted to tell senders to do so as a best effort--which is all we can guarantee from such a directive, since it depends upon sending behavior!--we would want to leverage the DNS anyway (if the lookups are frequent) to lower the cost of checking for a new policy (which usually will be false). No?

**Comment by prbinu** [comment]
> The problem with this is the "policy valid = no" flow. It means that you can only make
> breaking changes to your MX once the last served policy has expired (whereas in 
> the current design you can make breaking changes at any time as long as you are 
> serving a new policy).

Can you explain a bit more? I'm not entirely clear about the "breaking thing" you mentioned above. Actually the first diagram reflects the current proposal.

> The obvious implication of this compromise is that policy max_ages have to be 
> fairly short--probably a day is reasonable. The obvious implication of this is
> that once a day a MITM gets an opportunity.

What MITM issue are we referring here?

> (I agree there's a bit of complexity in STS as written around TTLs and refreshes, 
> which is absolutely something to try to clarify, but the complexity actually
> buys something specific: the ability to use a longer policy expiration time!)

Yes, I think we are not explaining in detail how to roll new polices (examples include MX changes, Report to enforce or vice-versa changes) without breaking the system. We need to clearly document it, and I believe TTLs and refreshes are mainly for this purpose.

**Comment by danmarg** [comment]
Sorry, I was referring to the modification where we don't do a DNS lookup on policy fetch. I probably should've commented on #62 instead. :) 

I agree we need to document this a bit better. My point about the DNS lookup is that it's a requirement to avoid lots of HTTP fetches on repeated validation failures (since it's a cheaper way of testing for a new policy). Conversely, my point about MITM was the risk of a low max-age, though there are ways around this (e.g. by having a high max-age but requiring frequent policy refreshes in a cron--but IMO that's not significantly cleaner or easier to implement). 

Anyway, let me comment more appropriately on #62. I like the state diagrams. I think for the second diagram, though, it's unclear to me that this is correct (but it might be): on expiration of a cached policy, do we go straight to HTTPS or again look for a TXT record? I'm not sure this is clearly written in the doc, but if we go with #62's suggestion it matters (and if we don't, it doesn't really).

**Comment by danmarg** [comment]
I think I mostly described the state machine (textually) in some recent edits, and https://github.com/mrisher/smtp-sts/pull/102 includes some psuedocode that may be better than the old (opinions welcome). 

I'm tempted to close this, as making a good diagram is something I'm not enthusiastic about doing, but

**Comment by prbinu** [comment]
Good diagram brings clarity to the parties interested in implementation. I would prefer a diagram than a lengthy description.

**Comment by danmarg** [comment]
Yeah, I'm OK with a diagram as long as someone else is making it. Not sure I can come up with a good one right now. :) 

@eyeofthenico may also want to take a look, since I think he's a bit closer to the implementation (and maybe thus the state flow).

**Comment by jjones425** [comment]
Once Nico takes a look and makes any changes I am happy to create a diagram. If nothing else, it will help us visually see the process flow.
